### ISSUE TITLE
Shell Lesson Data ZIP file is corrupt

### ISSUE THREAD

**Issue by kubu4** [suparee/2015-06-25-uw#1]
Unable to unzip the Shell Lesson Data. Cannot unzip via the shell or via GUI.

**Comment by benmarwick** [comment]
Thanks for noting this. I'm getting a 404 when I click on the links, maybe your unzipper is trying to unzip that 404 html page? We'll need to get the `data/` directory from the previous workshop and move it into this repo. That should fix it.

**Comment by kubu4** [comment]
Ah! Hadn't actually followed the link; just downloaded it. Probably exactly what's happening.

**Comment by suparee** [comment]
It should be fixed now.

**Comment by benmarwick** [comment]
Thanks very much, I've had a look and it now works as expected. Thanks again for fixing that.
